Repository CCC-org/keewe-backend, pull requests merged in 2023-07, with the labels that each got.

#324 [Feat] 애플 로그인 개발
  .gitsecret/paths/mapping.cfg
  build.gradle
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserSignUpController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/ui/AppleAuthController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/user/AppleSignUpRequest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserSignupControllerTest.java
  keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java
  keewe-core/src/main/resources/application-core.yml.secret
  keewe-domain/src/main/java/ccc/keewedomain/service/user/UserDomainService.java
  keewe-domain/src/main/resources/application-domain.yml.secret
  keewe-infra/src/main/java/ccc/keeweinfra/apis/oauth/AppleAuthApi.java
  keewe-infra/src/main/java/ccc/keeweinfra/dto/AppleProfileResponse.java
  keewe-infra/src/main/java/ccc/keeweinfra/dto/AppleTokenResponse.java
  keewe-infra/src/main/java/ccc/keeweinfra/service/oauth/AppleInfraService.java
Labels: enhancement

#338 [Feat] 탈퇴한 유저의 댓글/답글 처리
  keewe-api/src/main/java/ccc/keeweapi/component/CommentAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/ActiveUserCommentResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/ActiveUserPreviewCommentResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/ActiveUserReplyResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/CommentResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/DeletedUserReplyResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/PreviewCommentResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/ReplyResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/RepresentativeCommentsResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/WithdrawnUserCommentResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/WithdrawnUserPreviewCommentResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightCommentQueryApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightCommentControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/Comment.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/CommentQueryRepository.java
Labels: enhancement, feature

#345 [Feat] 챌린지 기록 테이블 추가
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/ChallengeRecord.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeRecordRepository.java
  keewe-domain/src/main/resources/ddl/ddl.sql
  keewe-domain/src/main/resources/ddl/user_token.sql
Labels: enhancement

#346 [Refactor] 챌린지 기록/성공/실패 처리 배치 리팩터링
  keewe-batch/src/main/java/ccc/keewebatch/batch/DailyChallengeRecorder.java
  keewe-core/src/main/java/ccc/keewecore/utils/DateTimeUtils.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeRecordRepository.java
Labels: refactoring
