Repository CCC-org/keewe-backend, pull requests merged in 2023-04, with the labels that each got.

#283 [Fix] 인사이트 최대 글자 수 400자로 수정
  keewe-domain/src/main/resources/ddl/ddl.sql
  keewe-domain/src/main/resources/dml/issue-278_dml.sql
Labels: bug

#282 [Feat] 알림 목록 조회 / 알림 읽음 처리 기능 개발
  keewe-api/src/main/java/ccc/keeweapi/controller/api/notification/NotificationController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/notification/NotificationResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/notification/PaginateNotificationResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentNotificationProcessor.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentReplyNotificationProcessor.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/NotificationProcessor.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/ReactionNotificationProcessor.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/TitleNotificationProcessor.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/command/.keep
  keewe-api/src/main/java/ccc/keeweapi/service/notification/command/NotificationCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/query/.keep
  keewe-api/src/main/java/ccc/keeweapi/service/notification/query/NotificationQueryApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/notification/NotificationControllerTest.java
  keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java
  keewe-core/src/main/java/ccc/keewecore/utils/ListUtils.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/Reaction.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/notification/Notification.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/notification/enums/NotificationCategory.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/notification/enums/NotificationContents.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/notification/NotificationQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/notification/NotificationRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/ReactionDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/notification/command/NotificationCommandDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/notification/query/NotificationQueryDomainService.java
  keewe-domain/src/main/resources/ddl/ddl.sql
  keewe-domain/src/main/resources/ddl/issue-#281_ddl.sql
Labels: feature

#287 [Feat] 차단한 유저에 대한 요청 필터링
  keewe-api/src/main/java/ccc/keeweapi/aop/BlockFilterAspect.java
  keewe-api/src/main/java/ccc/keeweapi/dto/InsightIdBlockRequest.java
  keewe-api/src/main/java/ccc/keeweapi/dto/UserIdBlockRequest.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/ReactRequest.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightReactionCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightDrawerQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java
  keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java
Labels: feature

#291 [Feat] 인사이트 통계 조회 API
  keewe-api/src/main/java/ccc/keeweapi/component/InsightAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/InsightStatisticsResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java
  keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/BookmarkQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/BookmarkQueryDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
Labels: feature

#303 [Feat] 인사이트 수정 기능 개발
  keewe-api/src/main/java/ccc/keeweapi/component/CommentAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/component/InsightAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/component/ReactionAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightBookmarkController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightCommentController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightDrawerController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightReactionController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/request/CommentCreateRequest.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/request/CommentDeleteRequest.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/request/DrawerCreateRequest.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/request/DrawerResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/request/DrawerUpdateRequest.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/request/InsightCreateRequest.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/request/InsightUpdateRequest.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/request/ReactRequest.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/BookmarkToggleResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/ChallengeRecordResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/CommentCreateResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/CommentDeleteResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/CommentResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/CommentWriterResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/DrawerCreateResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/InsightAuthorAreaResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/InsightCommentCountResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/InsightCreateResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/InsightDeleteResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/InsightGetForHomeResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/InsightGetResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/InsightMyPageResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/InsightStatisticsResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/InsightUpdateResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/InsightViewIncrementResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/PreviewCommentResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/ReactResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/ReactionAggregationResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/ReplyResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/insight/response/RepresentativeCommentsResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommentCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightDrawerCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightReactionCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightCommentQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightDrawerQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightBookmarkControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightCommentControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightDrawerControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightReactionControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/dto/insight/InsightUpdateDto.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/insight/Insight.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/command/InsightCommandDomainService.java
Labels: enhancement

#308 [Fix] 알림 응답 시 시간 정보 추가
  keewe-api/src/main/java/ccc/keeweapi/dto/notification/NotificationResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentNotificationProcessor.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentReplyNotificationProcessor.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/FollowNotificationProcessor.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/ReactionNotificationProcessor.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/TitleNotificationProcessor.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/notification/NotificationControllerTest.java
Labels: bug
