Repository CCC-org/keewe-backend, pull requests merged in 2023-06, with the labels that each got.

#332 [Fix] 마이페이지 응답에 참여중인 ChallengeId 추가
  keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/dto/user/ProfileMyPageResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserProfileControllerTest.java
Labels: enhancement

#331 [Fix] 최초 회원가입 타이틀 획득 버그 수정
  keewe-api/http/http-client.env.json
  keewe-api/http/signup.http
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserSignUpController.java
  keewe-api/src/main/java/ccc/keeweapi/service/user/UserApiService.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/enums/VendorType.java
  keewe-domain/src/main/java/ccc/keewedomain/service/user/UserDomainService.java
  keewe-infra/src/main/java/ccc/keeweinfra/dto/VirtualProfileResponse.java
Labels: bug

#334 [Feat] 팔로잉/팔로워 검색 API
  keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserInvitationController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/user/InviteeSearchResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserInvitationControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/FollowQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/cursor/InviteeSearchCursor.java
  keewe-domain/src/main/java/ccc/keewedomain/service/user/query/ProfileQueryDomainService.java
  keewe-domain/src/main/resources/ddl/ddl.sql
Labels: enhancement, feature
