Repository CCC-org/keewe-backend, pull requests merged in 2023-02, with the labels that each got.

#210 [NO-ISSUE] 챌린지 / 챌린지참여 컨트롤러 분리
  keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationController.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java
Labels: refactoring

#211 [NO-ISSUE] 유저 profile 컨트롤러 분리
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/ProfileController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserBlockController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserProfileController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserRelationController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserSignUpController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserTitleController.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/ProfileControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserBlockControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserProfileControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserRelationControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserSignupControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserTitleControllerTest.java
Labels: refactoring

#214 [NO-ISSUE] Insight 컨트롤러 정리
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightBookmarkController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightCommentController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightDrawerController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightReactionController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserBlockController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserProfileController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserRelationController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserSignUpController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserTitleController.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightBookmarkControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightCommentControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightDrawerControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightReactionControllerTest.java
Labels: refactoring

#217 [NO-ISSUE] Insight api service CQ 분리
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightBookmarkController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightCommentController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightDrawerController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightReactionController.java
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/command/.keep
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/query/.keep
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommentCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightDrawerCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightReactionCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightCommentQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightDrawerQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/report/command/.keep
  keewe-api/src/main/java/ccc/keeweapi/service/user/command/.keep
  keewe-api/src/main/java/ccc/keeweapi/service/user/query/.keep
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightBookmarkControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightCommentControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightDrawerControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightReactionControllerTest.java
Labels: refactoring

#219 [Github] PR, 이슈 탬플릿 추가
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#225 [Fix] 챌린지 참여 동시성 버그 수정
  keewe-core/src/main/java/ccc/keewecore/consts/KeeweRtnConsts.java
  keewe-core/src/main/java/ccc/keewecore/consts/LockType.java
  keewe-core/src/main/java/ccc/keewecore/utils/RedisLockUtils.java
  keewe-domain/src/main/java/ccc/keewedomain/service/challenge/ChallengeDomainService.java
Labels: bug

#216 [Feat] 챌린지 상세 함께 기록 조회 API, 챌린지 참가 중인 인원 조회 API
  keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/challenge/ChallengerCountResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/challenge/TogetherChallengerResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/challenge/ChallengeDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java
Labels: enhancement

#222 [Feat] 진행중인 챌린지 페이지네이션 조회 기능
  keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/challenge/OpenedChallengeResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/query/.keep
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/query/ChallengeQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/challenge/command/ChallengeCommandDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/challenge/query/ChallengeParticipateQueryDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/challenge/query/ChallengeQueryDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java
Labels: enhancement

#226 [Chore] API 문서 태그 분리
  keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightBookmarkControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightCommentControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightDrawerControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightReactionControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserBlockControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserProfileControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserRelationControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserSignupControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserTitleControllerTest.java
Labels: No Review
