Repository CCC-org/keewe-backend, pull requests merged in 2023-05, with the labels that each got.

#304 [Fix] 댓글 개수 조회 차단된 유저의 댓글 및 답글 제외
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightReactionCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightCommentQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightDrawerQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java
  keewe-api/src/main/java/ccc/keeweapi/utils/BlockUtil.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/CommentQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/CommentDomainService.java
Labels: enhancement

#311 [Feat] 참여 인원이 없는 챌린지 deleted 처리 배치 개발
  keewe-batch/src/main/java/ccc/keewebatch/batch/ChallengeRecordChecker.java
  keewe-batch/src/main/java/ccc/keewebatch/batch/NoOneParticipatedChallengeRemover.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/Challenge.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/ChallengeParticipation.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/challenge/command/ChallengeCommandDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/challenge/query/ChallengeParticipateQueryDomainService.java
  scripts/docker_mysql_macosm1.sh
Labels: enhancement

#312 [Fix] 미리보기에서 차단된 유저의 댓글을 제외
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommentCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightReactionCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightCommentQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightDrawerQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentNotificationProcessor.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/CommentReplyNotificationProcessor.java
  keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java
  keewe-api/src/main/java/ccc/keeweapi/utils/BlockedResourceManager.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/CommentQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/command/CommentCommandDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/CommentQueryDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/report/CommentReportDomainServiceImpl.java
  keewe-domain/src/test/java/ccc/keewedomain/service/insight/CommentDomainServiceTest.java
Labels: enhancement

#314 [Fix] 챌린지 참가 시 챌린지의 deleted 상태를 변경해요
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/Challenge.java
Labels: bug

#313 [Fix] 댓글 조회 API 쿼리에서 차단 필터링 적용
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightCommentQueryApiService.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/CommentQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/CommentQueryDomainService.java
Labels: enhancement

#316 [Feat] 친구 초대 대상 목록 조회 API
  keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserInvitationController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserRelationController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/user/InviteeListResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/user/InviteeResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserInvitationControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserRelationControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/FollowQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/UserQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/user/query/ProfileQueryDomainService.java
Labels: enhancement, feature

#319 [Feat] 미확인 알림 존재 여부 체크 기능 개발
  keewe-api/src/main/java/ccc/keeweapi/component/NotificationAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/notification/NotificationController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/notification/UnreadNotificationExistenceResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/notification/query/.keep
  keewe-api/src/main/java/ccc/keeweapi/service/notification/query/NotificationQueryApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/notification/NotificationControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/notification/NotificationQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/notification/query/NotificationQueryDomainService.java
Labels: feature

#317 [Feat] 설정 연결된 계정 API
  keewe-api/src/main/java/ccc/keeweapi/component/ProfileAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserProfileController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/user/AccountResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserProfileControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/User.java
Labels: enhancement, feature

#326 [Feat] 유저 탈퇴 기능 개발
  keewe-api/src/main/java/ccc/keeweapi/controller/api/user/UserSignUpController.java
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/user/ProfileApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/user/UserApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/user/UserSignupControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/user/User.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/FollowRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/UserQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/challenge/command/ChallengeCommandDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/title/AbstractTitleAcquireProcessor.java
  keewe-domain/src/main/java/ccc/keewedomain/service/title/InsightTitleAcquireProcessor.java
  keewe-domain/src/main/java/ccc/keewedomain/service/title/SignUpTitleAcquireProcessor.java
  keewe-domain/src/main/java/ccc/keewedomain/service/user/command/ProfileCommandDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/user/command/UserCommandDomainService.java
  keewe-infra/src/main/java/ccc/keeweinfra/service/image/S3StoreService.java
Labels: enhancement

#328 [Fix] 챌린지 ApiService에 readOnly Tx 제거
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java
Labels: bug

#330 [Fix] 챌린지-챌린지참가 Cascade 제거
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/Challenge.java
  keewe-domain/src/main/java/ccc/keewedomain/service/challenge/command/ChallengeCommandDomainService.java
Labels: bug
