Repository CCC-org/keewe-backend, pull requests merged in 2023-03, with the labels that each got.

#231 [Fix] DDL FK 추가
  keewe-domain/src/main/resources/ddl/ddl.sql
  keewe-domain/src/main/resources/dml/issue-230_dml.sql
Labels: bug

#237 [Feat] 완료된 챌린지 페이지네이션 조회
  keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeController.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/challenge/CompletedChallengeResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/query/ChallengeParticipationQueryApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeControllerTest.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/challenge/query/ChallengeParticipateQueryDomainService.java
Labels: enhancement

#238 [NO-ISSUE] 챌린지 페이지네이션 시 응답 필드 변경
  keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/dto/challenge/OpenedChallengeResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/query/ChallengeQueryApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeControllerTest.java
Labels: No Review

#240 [Feat] 완료된 챌린지 개수 조회 API 개발
  keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/challenge/FinishedChallengeCountResponse.java
  keewe-api/src/main/java/ccc/keeweapi/dto/challenge/FinishedChallengeResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/query/ChallengeParticipationQueryApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/challenge/query/ChallengeParticipateQueryDomainService.java
Labels: enhancement

#248 [Refactor] `InsightQueryDomainService`, `CommandDomainService` 분리
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/query/ChallengeQueryApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/command/InsightCommandApiService.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java
  keewe-batch/src/main/java/ccc/keewebatch/batch/ChallengeRecordCheckConfiguration.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/BookmarkQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/BookmarkRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/CommentDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/InsightDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/ReactionDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/command/BookmarkCommandDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/command/InsightCommandDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/BookmarkQueryDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
  keewe-domain/src/main/java/ccc/keewedomain/service/report/ReportDomainService.java
  keewe-domain/src/test/java/ccc/keewedomain/service/insight/InsightDomainServiceTest.java
  keewe-domain/src/test/java/ccc/keewedomain/service/insight/ReactionDomainServiceTest.java
  keewe-statistics/src/main/java/ccc/keewestatistics/listener/InsightViewListener.java
  keewe-statistics/src/test/java/ccc/keewestatistics/InsightReactTest.java
  keewe-statistics/src/test/java/ccc/keewestatistics/InsightViewIncrementTest.java
Labels: refactoring

#249 [Fix] Circular dependency remove
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
Labels: No Review

#255 [Feat] 인사이트 생성 시 챌린지 참가 현황 조회 API 수정 반영
  keewe-api/src/main/java/ccc/keeweapi/component/ChallengeAssembler.java
  keewe-api/src/main/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationController.java
  keewe-api/src/main/java/ccc/keeweapi/dto/challenge/MyParticipationProgressResponse.java
  keewe-api/src/main/java/ccc/keeweapi/service/challenge/ChallengeApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/challenge/ChallengeParticipationControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/domain/challenge/ChallengeParticipation.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
Labels: enhancement

#265 [Feat] 챌린지 상세 전체기록 페이지네이션 조회 API
  keewe-api/src/main/java/ccc/keeweapi/controller/api/insight/InsightController.java
  keewe-api/src/main/java/ccc/keeweapi/service/insight/query/InsightQueryApiService.java
  keewe-api/src/test/java/ccc/keeweapi/controller/api/insight/InsightControllerTest.java
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/insight/InsightQueryRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/insight/query/InsightQueryDomainService.java
Labels: enhancement

#267 [Fix] existsByChallengerIdAndStatus 쿼리 경로 수정
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/challenge/ChallengeParticipationQueryRepository.java
Labels: bug

#268 [Fix] follow 존재할 때만 delete
  keewe-domain/src/main/java/ccc/keewedomain/persistence/repository/user/FollowRepository.java
  keewe-domain/src/main/java/ccc/keewedomain/service/user/ProfileDomainService.java
Labels: bug
